### ISSUE TITLE
Embed visualization in website

### ISSUE THREAD

**Issue by olafgrabienski** [olafgrabienski/vega-fortext#10]
In https://github.com/olafgrabienski/vega-fortext/pull/9 the `deploy` folder was added to the code. Information by @mpetris :

- `datamanagement.js` and `visualization-edge-bundling.vg.json` need to be deployed to the fortext site
  - `datamanagement.js` is imported into the template via an import statement
  - `visualization-edge-bundling.vg.json` is loaded with the fetch function within the embedded code
  - both have to be present as files
- `embed-module.html` contains the four script imports and the code to be embedded into the front page (div+script)

**Comment by olafgrabienski** [comment]
Integration in Backdrop CMS:

- [ ] Put the `.js` file and the `.json` file in the `js` folder of the theme.
- [ ] Put the `html` parts in the template file `page.tpl.php`, if the node ID corresponds to the home page.

**Comment by olafgrabienski** [comment]
I've embedded the visualization on a test page, that works!

Follow-ups:

- Consider how changed paths should be reflected in the code here on Github.
- Improve visualization for the website dimensions.
- Put visualization on home page, and change intro text if necessary.

**Comment by mpetris** [comment]
What do yo mean by 'paths'?
The dimensions of the visualization can be configured within the Vega Script: `width`, `height`, `radius`, `innerRadius `and `outerRadius`.

**Comment by olafgrabienski** [comment]
By 'paths' I mean the path to the new locations of the JS file and the JSON file. I've put the files in a folder of the theme.

**Comment by olafgrabienski** [comment]
Thanks for the hint of the visualization dimensions. Do you know if it's also possible to change the position of the legend? My idea is to push the "Kategorie" legend down, so that the circle has more space to the left (and can move to the left).

**Comment by olafgrabienski** [comment]
@mpetris Changing for instance `width` in the `visualization-edge-bundling.vg.json` file which had been deployed to the website, doesn't change the dimensions. Do I have to change it also in the file located in the repo root?

**Comment by olafgrabienski** [comment]
Strange, I've tried it again, and now a change of `width` and `height` is visible on the test page of the website.

However, you said, when I make the width smaller and the height bigger (see the new values below), then the legends would be placed under the circle. In a way, the legends now *are* below the circle, but that doesn't lead to the desired reduction of white space, and the circle still isn't left-aligned.

Original:
```
"width": 770,
"height": 720,
```

New:
```
"width": 710,
"height": 920,
```

**Comment by olafgrabienski** [comment]
l'll better wait for hints how to change the dimensions and placement of single elements (circle, and legends).

My goal is to have as less white space as possible, so that the circle uses all of the available width. Based on this result, I'd like to set the a `max-width` via CSS for a decent presentation on narrower screens.

**Comment by mpetris** [comment]
Pull request #11 should fix the problem with the excessive whitespace on top. It also places the legends below the visualization. A `min-width: 645px` of `.l-content.col-md-9` the class of the main column should prevent that the news column overlaps with the visualization when shrinking horizontally. @olafgrabienski  I hope that could be applied to the CSS somewhere.

**Comment by mpetris** [comment]
> doesn't change the dimensions.

I noticed that sometimes the caching of the browser is too aggressive and changes only apply after actively clearing the cache. Maybe that was the problem.

**Comment by mpetris** [comment]
I already updated the test page, so the changes of #11 are in effect already.

**Comment by olafgrabienski** [comment]
> I already updated the test page, so the changes of #11 are in effect already.

Thanks for updating the test page! What exactly have you updated? And should I merge #11 anyway?

**Comment by mpetris** [comment]
Yes, the merge reflects the changes I made to the Vega Spec and the datamanagement.js embedded in the test page.

**Comment by olafgrabienski** [comment]
Ok, merged!

**Comment by olafgrabienski** [comment]
>  A `min-width: 645px` of `.l-content.col-md-9` (...) should prevent that the news column overlaps with the visualization when shrinking horizontally.

A min-width for that column may be problematic but I'll have a look at it and will think about alternatives for a reasonable display on smaller screens.

**Comment by olafgrabienski** [comment]
I've embedded the visualization on the home page and set a `max-width` for the canvas element, to make sure that the visualization doesn't overlap with the sidebar:

```
canvas.marks {
  max-width: 100%;
  height: auto !important;
}
```

The `auto !important` value for `height` is only needed in some situations where the height gets applied as inline style. (Can't reproduce it at the moment, but I guess this fallback value does no harm.)

> A min-width for that column may be problematic (...)

For reference: being a responsive class primarily defining width for several media queries, `col-md-9` wouldn't work well with a `min-width`.

**Comment by olafgrabienski** [comment]
> I've embedded the visualization on the home page and set a max-width for the canvas element, to make sure that the visualization doesn't overlap with the sidebar

Working with `max-width` we have some room to make the visualization wider. I'll close this issue and will file a separate follow-up for this.
