### ISSUE TITLE
better handing of long article names 

### ISSUE THREAD

**Issue by mpetris** [olafgrabienski/vega-fortext#4]

**Comment by olafgrabienski** [comment]
We could also use shorter article names / titles. On the [forTEXT website](https://fortext.net), there are two kind of titles: the regular node title, and a (in most cases) shorter title of the respective menu item. Example:

- Kollaboratives literaturwissenschaftliches Annotieren (node title, 53 characters)
- Kollaborative Annotation (menu item title, 24 characters)

I'm not sure if it's possible to provide the menu item titles in the View, I'll have a look at it.

**Comment by olafgrabienski** [comment]
It turned out that it's not easily possible to provide menu item titles in a content view. As a workaround, we're going to use a separate field on the content types. I've already created the `field_title_short`.

**Comment by olafgrabienski** [comment]
Fixed via https://github.com/olafgrabienski/vega-fortext/pull/8.
